site_name: ThanoSQL
site_description: AI개발이 가능한 세상의 모든 비정형 데이터를 SQL로
site_url: https://docs.thanosql.ai/en
site_author: Smartmind Team
theme:
  name: material
  logo: assets/images/docs_logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
plugins:
  - search
#   - git-revision-date-localized:
#       type: iso_date
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
repo_name: smartmind-team/thanosql-docs
repo_url: https://github.com/smartmind-team/thanosql-docs
edit_uri: ""

nav:
  - 개요:
      - What is ThanoSQL?: index.md
      - 빠른 시작 (Quick Start):
          - ThanoSQL 워크스페이스 사용법: quick_start/hello_ThanoSQL.md

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 한국어
      link: /
      lang: ko
  analytics:
    provider: google
    property: G-8KVG4NMMFK

extra_css:
  - /assets/css/extra.css
